### ISSUE TITLE
Direct printing (CUPS)

### ISSUE THREAD

**Issue by shadow046** [ormelflores/pos#14]
![image](https://github.com/ormelflores/pos/assets/53925724/de32b0db-24a4-4384-8494-41d439f58ecf)

i got this error.. i already install composer require guzzlehttp/guzzle but still same problem.

**Comment by ormelflores** [comment]
@shadow046 I forgot to install this`composer require smalot/cups-ipp`. It should be working now, just check the recent releases

**Comment by shadow046** [comment]
> @shadow046 I forgot to install this`composer require smalot/cups-ipp`. It should be working now, just check the recent releases

thanks for this.. i will try

**Comment by shadow046** [comment]
![image](https://github.com/ormelflores/pos/assets/53925724/b714d505-0fbf-4bcf-8815-d6ea06ed1b76)

new error i cant fix it.

**Comment by ormelflores** [comment]
@shadow046 I did not encounter that error. It might be related to this https://github.com/rawilk/laravel-printing/issues/74

**Comment by shadow046** [comment]
> @shadow046 I did not encounter that error. It might be related to this [rawilk/laravel-printing#74](https://github.com/rawilk/laravel-printing/issues/74)

i think this is related to smalot/cups-ipp its not updated.. i saw this issue there too.
